stages:
  TestTraining:
    cmd: python src\train_model.py
    deps:
    - dataset\prepared\datasets_v002.pkl
    - src\train_model.py
    params:
    - train.test_size
    outs:
    - model
  TestInference:
    cmd: python src\inference.py
    deps:
    - model\model_v001.pkl
    - src\inference.py
    params:
    - inference.n_test
    outs:
    - score
  TestEvaluate:
    cmd: python src\evaluate.py
    deps:
    - model\model_v001.pkl
    - src\evaluate.py
    metrics:
    - inference\score.txt:
        cache: false
  updateDataset:
    cmd: python src\updateDataset.py 10
    deps:
    - dataset\original\datasets_v001.pkl
    - params.yaml
    - src\updateDataset.py
    outs:
    - dataset\prepared
