stages:
  testCreateDataset:
    cmd: python src\createDataset.py 10
    deps:
    - src\createDataset.py
    outs:
    - dataset\original
    - dataset\prepared
  TestTraining:
    cmd: python src\train_model.py
    deps:
    - src\train_model.py
    params:
    - train.test_size
  TestInference:
    cmd: python src\inference.py
    deps:
    - model\model_v001.pkl
    - src\inference.py
    params:
    - inference.n_test
    outs:
    - score
  TestEvaluate:
    cmd: python src\evaluate.py
    deps:
    - model\model_v001.pkl
    - src\evaluate.py
    metrics:
    - inference\score.txt:
        cache: false
